# Generated by Django 4.1.7 on 2023-02-19 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='perevalapi.record'),
        ),
        migrations.AlterField(
            model_name='record',
            name='beauty_title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Название 1'),
        ),
        migrations.AlterField(
            model_name='record',
            name='other_title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Название 3'),
        ),
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Название 2'),
        ),
    ]
