# Generated by Django 4.1.7 on 2023-02-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapi', '0002_alter_images_record_alter_record_beauty_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.BinaryField(verbose_name='Фото'),
        ),
    ]
